import type { Campaign } from "@/lib/types";

export const campaigns: Campaign[] = [
  {
    id: "lg-1001",
    title: "Restore Green Lane Mosque Community Hall",
    creatorName: "Amina Rahman",
    creatorLocation: "Birmingham, United Kingdom",
    beneficiaryLocation: "Birmingham, United Kingdom",
    category: "Mosque renovation",
    goalAmount: 18000,
    currency: "USD",
    submittedAt: "2026-05-23T04:10:00+03:00",
    slaHours: 24,
    riskTier: "LOW",
    confidence: 0.94,
    status: "New",
    accountAgeDays: 1480,
    previousCampaigns: 6,
    sanctionsScreen: "pass",
    description:
      "Repeat community organizer raising funds to repair roof damage, upgrade accessibility ramps, and reopen the hall for weekend youth programs.",
    documentsSubmitted: ["charity_registration", "bank_verification", "quote_invoice", "trustee_id"],
    missingDocuments: [],
    riskSignals: ["Construction work requires invoice review"],
    positiveSignals: [
      "Repeat creator with six completed campaigns",
      "UK charity registration provided",
      "Bank account matches mosque legal entity"
    ],
    recommendedAction: "APPROVE_REVIEW",
    reviewerNote: "Routine mosque renovation with complete documentation and known creator history."
  },
  {
    id: "lg-1002",
    title: "Emergency Medical Support for Saleh in Sana'a",
    creatorName: "Omar Haddad",
    creatorLocation: "Dearborn, United States",
    beneficiaryLocation: "Sana'a, Yemen",
    category: "Medical emergency",
    goalAmount: 32000,
    currency: "USD",
    submittedAt: "2026-05-22T19:35:00+03:00",
    slaHours: 12,
    riskTier: "MEDIUM",
    confidence: 0.83,
    status: "In review",
    accountAgeDays: 18,
    previousCampaigns: 0,
    sanctionsScreen: "pass",
    description:
      "First-time creator raising funds for a cousin's urgent cardiac procedure and hospital stay in Yemen, with partial medical paperwork uploaded.",
    documentsSubmitted: ["creator_id", "medical_letter"],
    missingDocuments: ["beneficiary_id", "bank_verification"],
    riskSignals: ["Beneficiary in enhanced due diligence jurisdiction", "First-time creator", "Missing beneficiary ID"],
    positiveSignals: ["Medical letter is specific", "Sanctions screen passed", "Creator identity verified"],
    recommendedAction: "REQUEST_DOCUMENTS",
    reviewerNote: "Likely legitimate but Yemen beneficiary requires EDD document set before approval."
  },
  {
    id: "lg-1003",
    title: "Winter Relief Parcels for Displaced Gaza Families",
    creatorName: "Nour Collective",
    creatorLocation: "Toronto, Canada",
    beneficiaryLocation: "Gaza, Palestinian Territories",
    category: "Emergency relief",
    goalAmount: 80000,
    currency: "USD",
    submittedAt: "2026-05-22T15:10:00+03:00",
    slaHours: 8,
    riskTier: "HIGH",
    confidence: 0.88,
    status: "In review",
    accountAgeDays: 6,
    previousCampaigns: 0,
    sanctionsScreen: "pending",
    description:
      "New account requesting a large relief raise. Description names broad aid categories but does not identify implementing partners or distribution controls.",
    documentsSubmitted: ["creator_id"],
    missingDocuments: ["partner_mou", "distribution_plan", "bank_verification", "beneficiary_org_registration"],
    riskSignals: ["Large goal for new account", "Sensitive beneficiary location", "Incomplete implementation details"],
    positiveSignals: ["Creator ID uploaded", "Cause category is consistent with current needs"],
    recommendedAction: "SENIOR_REVIEW",
    reviewerNote: "Needs senior review and partner verification before any creator communication promises progress."
  },
  {
    id: "lg-1004",
    title: "Orphan Sponsorship Fund for Al Noor Network",
    creatorName: "Khaled Mansour",
    creatorLocation: "Istanbul, Turkiye",
    beneficiaryLocation: "Idlib, Syria",
    category: "Orphan support",
    goalAmount: 27000,
    currency: "USD",
    submittedAt: "2026-05-22T09:42:00+03:00",
    slaHours: 4,
    riskTier: "ESCALATE",
    confidence: 0.96,
    status: "Escalated",
    accountAgeDays: 2,
    previousCampaigns: 0,
    sanctionsScreen: "confirmed_hit",
    description:
      "Campaign references a local aid network and includes a contact whose name matches a confirmed sanctions screening result.",
    documentsSubmitted: ["creator_id"],
    missingDocuments: ["compliance_clearance"],
    riskSignals: ["Confirmed sanctions screening hit", "New creator", "Sensitive operating region"],
    positiveSignals: ["Creator provided government ID"],
    recommendedAction: "ESCALATE_COMPLIANCE",
    reviewerNote: "Immediate compliance escalation. Do not contact creator until compliance gives guidance."
  },
  {
    id: "lg-1005",
    title: "Clean Water Wells for Kelantan Villages",
    creatorName: "Pertubuhan Ihsan Malaysia",
    creatorLocation: "Kuala Lumpur, Malaysia",
    beneficiaryLocation: "Kelantan, Malaysia",
    category: "NGO project",
    goalAmount: 24000,
    currency: "USD",
    submittedAt: "2026-05-23T01:24:00+03:00",
    slaHours: 18,
    riskTier: "MEDIUM",
    confidence: 0.79,
    status: "Waiting on creator",
    accountAgeDays: 210,
    previousCampaigns: 1,
    sanctionsScreen: "pass",
    description:
      "Registered NGO seeking funds to install two wells and water filters for flood-affected rural communities.",
    documentsSubmitted: ["bank_verification", "project_budget"],
    missingDocuments: ["ngo_incorporation", "authorized_signatory_id"],
    riskSignals: ["Missing incorporation documents", "Funds collected for NGO disbursement"],
    positiveSignals: ["Sanctions screen passed", "Budget is itemized", "Previous small campaign completed"],
    recommendedAction: "REQUEST_DOCUMENTS",
    reviewerNote: "Request NGO registration and signatory ID before approval."
  },
  {
    id: "lg-1006",
    title: "Wheelchair Ramp for Masjid Al Huda",
    creatorName: "Bilal Khan",
    creatorLocation: "Chicago, United States",
    beneficiaryLocation: "Chicago, United States",
    category: "Accessibility",
    goalAmount: 9500,
    currency: "USD",
    submittedAt: "2026-05-23T06:05:00+03:00",
    slaHours: 24,
    riskTier: "LOW",
    confidence: 0.91,
    status: "New",
    accountAgeDays: 760,
    previousCampaigns: 3,
    sanctionsScreen: "pass",
    description:
      "Local masjid board member fundraising for a contractor-built wheelchair ramp and entryway repairs with quote attached.",
    documentsSubmitted: ["board_authorization", "contractor_quote", "bank_verification", "creator_id"],
    missingDocuments: [],
    riskSignals: ["Minor construction verification needed"],
    positiveSignals: ["Repeat creator", "Complete project documentation", "Low domestic goal"],
    recommendedAction: "APPROVE_REVIEW",
    reviewerNote: "Low-risk domestic accessibility improvement."
  },
  {
    id: "lg-1007",
    title: "Food Baskets for Flooded Families in Sylhet",
    creatorName: "Mariam Chowdhury",
    creatorLocation: "London, United Kingdom",
    beneficiaryLocation: "Sylhet, Bangladesh",
    category: "Disaster relief",
    goalAmount: 41000,
    currency: "USD",
    submittedAt: "2026-05-22T22:18:00+03:00",
    slaHours: 12,
    riskTier: "MEDIUM",
    confidence: 0.81,
    status: "New",
    accountAgeDays: 95,
    previousCampaigns: 0,
    sanctionsScreen: "pass",
    description:
      "Creator is coordinating with relatives and a local volunteer team to distribute rice, lentils, oil, and hygiene kits after seasonal flooding.",
    documentsSubmitted: ["creator_id", "distribution_budget"],
    missingDocuments: ["local_partner_reference", "bank_verification"],
    riskSignals: ["First campaign", "International cash movement", "Missing local partner reference"],
    positiveSignals: ["Detailed relief budget", "Sanctions screen passed", "Specific district and item list"],
    recommendedAction: "REQUEST_DOCUMENTS",
    reviewerNote: "Request partner reference and receiving bank verification."
  },
  {
    id: "lg-1008",
    title: "Rebuild Classrooms for Al Amal School",
    creatorName: "Hope Bridge Education",
    creatorLocation: "Amman, Jordan",
    beneficiaryLocation: "Amman, Jordan",
    category: "Education",
    goalAmount: 56000,
    currency: "USD",
    submittedAt: "2026-05-21T17:55:00+03:00",
    slaHours: 10,
    riskTier: "HIGH",
    confidence: 0.84,
    status: "In review",
    accountAgeDays: 31,
    previousCampaigns: 0,
    sanctionsScreen: "name_match",
    description:
      "Education project with a sizeable construction budget. Sanctions screening produced an unresolved name match for one listed director.",
    documentsSubmitted: ["ngo_incorporation", "project_budget", "director_id"],
    missingDocuments: ["name_match_attestation", "board_resolution", "contractor_quote"],
    riskSignals: ["Unresolved sanctions name match", "Large construction budget", "New organization account"],
    positiveSignals: ["NGO registration uploaded", "Budget categories included"],
    recommendedAction: "SENIOR_REVIEW",
    reviewerNote: "Senior reviewer should resolve name match and validate school authorization."
  },
  {
    id: "lg-1009",
    title: "Ramadan Iftar Kitchen in Paterson",
    creatorName: "Safa Community Center",
    creatorLocation: "Paterson, United States",
    beneficiaryLocation: "Paterson, United States",
    category: "Food aid",
    goalAmount: 12500,
    currency: "USD",
    submittedAt: "2026-05-23T05:42:00+03:00",
    slaHours: 24,
    riskTier: "LOW",
    confidence: 0.93,
    status: "New",
    accountAgeDays: 980,
    previousCampaigns: 8,
    sanctionsScreen: "pass",
    description:
      "Community center preparing weekly iftar meals for seniors, refugees, and students using the same kitchen partner as prior years.",
    documentsSubmitted: ["nonprofit_letter", "bank_verification", "food_permit", "budget"],
    missingDocuments: [],
    riskSignals: [],
    positiveSignals: ["Longstanding creator", "Same verified bank account", "Food permit attached"],
    recommendedAction: "APPROVE_REVIEW",
    reviewerNote: "Routine repeat campaign."
  },
  {
    id: "lg-1010",
    title: "Support for Ahmed's Kidney Treatment",
    creatorName: "Layla Osman",
    creatorLocation: "Doha, Qatar",
    beneficiaryLocation: "Khartoum, Sudan",
    category: "Medical emergency",
    goalAmount: 22000,
    currency: "USD",
    submittedAt: "2026-05-22T11:30:00+03:00",
    slaHours: 12,
    riskTier: "MEDIUM",
    confidence: 0.77,
    status: "Waiting on creator",
    accountAgeDays: 44,
    previousCampaigns: 0,
    sanctionsScreen: "pass",
    description:
      "Medical fundraiser for dialysis and travel costs. Hospital estimate is attached but beneficiary identity and receiving account are missing.",
    documentsSubmitted: ["creator_id", "hospital_estimate"],
    missingDocuments: ["beneficiary_id", "bank_verification", "relationship_attestation"],
    riskSignals: ["Beneficiary in EDD region", "First-time creator", "Missing relationship attestation"],
    positiveSignals: ["Hospital estimate uploaded", "Sanctions screen passed"],
    recommendedAction: "REQUEST_DOCUMENTS",
    reviewerNote: "Ask for beneficiary ID, relationship attestation, and receiving bank verification."
  },
  {
    id: "lg-1011",
    title: "Zakat Fund for Verified Local Families",
    creatorName: "Mercy Hands Australia",
    creatorLocation: "Melbourne, Australia",
    beneficiaryLocation: "Melbourne, Australia",
    category: "Zakat distribution",
    goalAmount: 30000,
    currency: "USD",
    submittedAt: "2026-05-23T02:02:00+03:00",
    slaHours: 24,
    riskTier: "LOW",
    confidence: 0.9,
    status: "New",
    accountAgeDays: 1120,
    previousCampaigns: 5,
    sanctionsScreen: "pass",
    description:
      "Registered charity distributing zakat to pre-screened families through an established internal casework process.",
    documentsSubmitted: ["charity_registration", "zakat_policy", "bank_verification", "casework_summary"],
    missingDocuments: [],
    riskSignals: ["Zakat claims require policy consistency check"],
    positiveSignals: ["Zakat policy attached", "Registered charity", "Strong creator history"],
    recommendedAction: "APPROVE_REVIEW",
    reviewerNote: "Low-risk repeat charity with complete zakat documentation."
  },
  {
    id: "lg-1012",
    title: "Emergency Shelter for Earthquake Survivors",
    creatorName: "Anatolia Relief Forum",
    creatorLocation: "Berlin, Germany",
    beneficiaryLocation: "Aleppo, Syria",
    category: "Emergency relief",
    goalAmount: 70000,
    currency: "USD",
    submittedAt: "2026-05-21T13:20:00+03:00",
    slaHours: 8,
    riskTier: "HIGH",
    confidence: 0.86,
    status: "In review",
    accountAgeDays: 14,
    previousCampaigns: 0,
    sanctionsScreen: "pending",
    description:
      "Large shelter campaign using a new relief forum account. The campaign references field teams but does not provide partner contracts or beneficiary controls.",
    documentsSubmitted: ["creator_id", "budget"],
    missingDocuments: ["partner_mou", "distribution_plan", "beneficiary_org_registration", "bank_verification"],
    riskSignals: ["High goal", "Sensitive beneficiary location", "New account", "Pending sanctions screening"],
    positiveSignals: ["Budget uploaded", "Creator ID verified"],
    recommendedAction: "SENIOR_REVIEW",
    reviewerNote: "Hold for senior review and partner verification."
  },
  {
    id: "lg-1013",
    title: "Legal Aid for Detained Students",
    creatorName: "Student Justice Circle",
    creatorLocation: "Paris, France",
    beneficiaryLocation: "Paris, France",
    category: "Legal aid",
    goalAmount: 19000,
    currency: "USD",
    submittedAt: "2026-05-22T08:08:00+03:00",
    slaHours: 10,
    riskTier: "HIGH",
    confidence: 0.8,
    status: "New",
    accountAgeDays: 3,
    previousCampaigns: 0,
    sanctionsScreen: "pass",
    description:
      "New collective raising legal fees for unnamed students. Campaign uses urgent language but omits law firm engagement details and beneficiary consent.",
    documentsSubmitted: ["creator_id"],
    missingDocuments: ["law_firm_letter", "beneficiary_consent", "use_of_funds_breakdown"],
    riskSignals: ["Unnamed beneficiaries", "Legal defense category", "New account", "Sparse use-of-funds details"],
    positiveSignals: ["Sanctions screen passed"],
    recommendedAction: "SENIOR_REVIEW",
    reviewerNote: "Needs senior review due to legal aid sensitivity and incomplete beneficiary details."
  },
  {
    id: "lg-1014",
    title: "Community Pantry Restock in Queens",
    creatorName: "Masjid Taqwa Pantry Team",
    creatorLocation: "Queens, United States",
    beneficiaryLocation: "Queens, United States",
    category: "Food aid",
    goalAmount: 6800,
    currency: "USD",
    submittedAt: "2026-05-23T07:12:00+03:00",
    slaHours: 24,
    riskTier: "LOW",
    confidence: 0.95,
    status: "New",
    accountAgeDays: 640,
    previousCampaigns: 4,
    sanctionsScreen: "pass",
    description:
      "Small domestic pantry restock fundraiser with grocery quotes and distribution dates for local families.",
    documentsSubmitted: ["bank_verification", "budget", "masjid_authorization"],
    missingDocuments: [],
    riskSignals: [],
    positiveSignals: ["Low amount", "Repeat creator", "Complete domestic food-aid documents"],
    recommendedAction: "APPROVE_REVIEW",
    reviewerNote: "Routine domestic food-aid campaign."
  },
  {
    id: "lg-1015",
    title: "Livelihood Grants for Widows in Lahore",
    creatorName: "Sakeena Foundation",
    creatorLocation: "Lahore, Pakistan",
    beneficiaryLocation: "Lahore, Pakistan",
    category: "Livelihood support",
    goalAmount: 36000,
    currency: "USD",
    submittedAt: "2026-05-22T18:44:00+03:00",
    slaHours: 14,
    riskTier: "MEDIUM",
    confidence: 0.78,
    status: "In review",
    accountAgeDays: 300,
    previousCampaigns: 2,
    sanctionsScreen: "pass",
    description:
      "Foundation wants to provide sewing machines and microgrants to widows, with a beneficiary selection summary but no current registration renewal.",
    documentsSubmitted: ["bank_verification", "beneficiary_selection_summary", "prior_report"],
    missingDocuments: ["ngo_registration_renewal", "authorized_signatory_id"],
    riskSignals: ["Cash-equivalent microgrants", "Missing current registration renewal"],
    positiveSignals: ["Prior campaign report uploaded", "Sanctions screen passed", "Known organization"],
    recommendedAction: "REQUEST_DOCUMENTS",
    reviewerNote: "Request current registration renewal and authorized signatory ID."
  },
  {
    id: "lg-1016",
    title: "Medical Debt Relief for Sister Hana",
    creatorName: "Yusuf Ali",
    creatorLocation: "Manchester, United Kingdom",
    beneficiaryLocation: "Manchester, United Kingdom",
    category: "Medical debt",
    goalAmount: 14500,
    currency: "USD",
    submittedAt: "2026-05-22T21:05:00+03:00",
    slaHours: 16,
    riskTier: "MEDIUM",
    confidence: 0.74,
    status: "New",
    accountAgeDays: 70,
    previousCampaigns: 0,
    sanctionsScreen: "pass",
    description:
      "Creator is fundraising for a family member's private treatment invoice. Documents show the invoice but not beneficiary consent.",
    documentsSubmitted: ["creator_id", "medical_invoice"],
    missingDocuments: ["beneficiary_consent", "relationship_attestation"],
    riskSignals: ["First campaign", "Personal medical beneficiary", "Missing consent"],
    positiveSignals: ["Domestic campaign", "Invoice uploaded", "Sanctions screen passed"],
    recommendedAction: "REQUEST_DOCUMENTS",
    reviewerNote: "Request consent and relationship attestation."
  },
  {
    id: "lg-1017",
    title: "Rehouse Families After Apartment Fire",
    creatorName: "Iman Services",
    creatorLocation: "Minneapolis, United States",
    beneficiaryLocation: "Minneapolis, United States",
    category: "Emergency housing",
    goalAmount: 21000,
    currency: "USD",
    submittedAt: "2026-05-23T03:48:00+03:00",
    slaHours: 24,
    riskTier: "LOW",
    confidence: 0.89,
    status: "New",
    accountAgeDays: 530,
    previousCampaigns: 2,
    sanctionsScreen: "pass",
    description:
      "Local nonprofit raising funds for temporary hotel stays and deposits after a verified apartment fire displaced families.",
    documentsSubmitted: ["nonprofit_letter", "incident_report", "bank_verification", "budget"],
    missingDocuments: [],
    riskSignals: ["Emergency timeline"],
    positiveSignals: ["Incident report attached", "Known nonprofit", "Domestic beneficiary location"],
    recommendedAction: "APPROVE_REVIEW",
    reviewerNote: "Low-risk emergency housing campaign with supporting documents."
  },
  {
    id: "lg-1018",
    title: "Aid Convoy Fuel and Supplies",
    creatorName: "Border Mercy Initiative",
    creatorLocation: "Gaziantep, Turkiye",
    beneficiaryLocation: "Northern Syria",
    category: "Cross-border relief",
    goalAmount: 62000,
    currency: "USD",
    submittedAt: "2026-05-21T10:16:00+03:00",
    slaHours: 4,
    riskTier: "ESCALATE",
    confidence: 0.91,
    status: "Escalated",
    accountAgeDays: 9,
    previousCampaigns: 0,
    sanctionsScreen: "name_match",
    description:
      "Cross-border aid campaign lists a logistics coordinator with an unresolved sanctions name match and requests fuel funding for convoy operations.",
    documentsSubmitted: ["creator_id", "budget"],
    missingDocuments: ["compliance_clearance", "partner_mou", "route_controls"],
    riskSignals: ["Sanctions name match", "Cross-border convoy activity", "Fuel funding", "New account"],
    positiveSignals: ["Budget uploaded"],
    recommendedAction: "ESCALATE_COMPLIANCE",
    reviewerNote: "Escalate to compliance due to sanctions name match and cross-border logistics risk."
  },
  {
    id: "lg-1019",
    title: "Funeral Support for the Nasser Family",
    creatorName: "Samira Nasser",
    creatorLocation: "Detroit, United States",
    beneficiaryLocation: "Detroit, United States",
    category: "Funeral support",
    goalAmount: 11000,
    currency: "USD",
    submittedAt: "2026-05-23T00:58:00+03:00",
    slaHours: 18,
    riskTier: "MEDIUM",
    confidence: 0.76,
    status: "New",
    accountAgeDays: 11,
    previousCampaigns: 0,
    sanctionsScreen: "pass",
    description:
      "Urgent funeral fundraiser with a funeral home estimate, but the receiving account is personal and needs verification.",
    documentsSubmitted: ["creator_id", "funeral_home_estimate"],
    missingDocuments: ["bank_verification", "relationship_attestation"],
    riskSignals: ["First-time creator", "Personal receiving account", "Urgent bereavement category"],
    positiveSignals: ["Domestic campaign", "Funeral estimate attached", "Sanctions screen passed"],
    recommendedAction: "REQUEST_DOCUMENTS",
    reviewerNote: "Request bank verification and relationship attestation."
  },
  {
    id: "lg-1020",
    title: "Solar Panels for Rural Quran School",
    creatorName: "Nur Education Trust",
    creatorLocation: "Nairobi, Kenya",
    beneficiaryLocation: "Garissa, Kenya",
    category: "Education infrastructure",
    goalAmount: 28000,
    currency: "USD",
    submittedAt: "2026-05-22T12:48:00+03:00",
    slaHours: 14,
    riskTier: "MEDIUM",
    confidence: 0.8,
    status: "In review",
    accountAgeDays: 420,
    previousCampaigns: 1,
    sanctionsScreen: "pass",
    description:
      "Education trust fundraising for solar panels and batteries at a rural school, with vendor quotes but incomplete board authorization.",
    documentsSubmitted: ["trust_registration", "vendor_quote", "bank_verification"],
    missingDocuments: ["board_authorization", "school_letter"],
    riskSignals: ["Infrastructure purchase", "Missing school authorization"],
    positiveSignals: ["Registered trust", "Vendor quote attached", "Sanctions screen passed"],
    recommendedAction: "REQUEST_DOCUMENTS",
    reviewerNote: "Request school letter and board authorization before approval."
  }
];

export function getCampaign(id: string) {
  return campaigns.find((campaign) => campaign.id === id);
}
